---
# The format of this file is documented here:
# https://github.com/langchain4j/langchain4j-github-bot
features: [TRIAGE_ISSUES_AND_PULL_REQUESTS]
triage:
  rules:
    - id: azure
      labels: [Azure]
      title: "azure"
      notify: [gsmet,langchain4j]
      notifyInPullRequest: true
      files:
        - '*-azure-*/**'
