---
# The format of this file is documented here:
# https://github.com/quarkusio/quarkus-bot/#triage-issues
triage:
  rules:
    - labels: [area/amazon-lambda]
      title: "(?i).*lambda.*"
      notify: [patriot1burke, matejvasek]
      directories:
        - extensions/amazon-lambda
        - integration-tests/amazon-lambda
    - labels: [area/persistence]
      titleBody: "(?i).*db2.*"
      notify: [aguibert]
      directories:
        - extensions/reactive-db2-client/
        - extensions/jdbc/jdbc-db2/
    - labels: [area/funqy]
      titleBody: "(?i).*funqy.*"
      notify: [patriot1burke, matejvasek]
      directories:
        - extensions/funqy/
    - labels: [area/devmode]
      titleBody: "dev mode"
    - labels: [area/gradle]
      title: "(?i).*gradle.*"
      notify: [quarkusio/devtools, glefloch]
      directories:
        - devtools/gradle/
        - integration-tests/gradle/
    - labels: [area/maven]
      title: "(?i).*maven.*"
      notify: [quarkusio/devtools]
      directories:
        - devtools/maven/
        - integration-tests/maven/
        - independent-projects/bootstrap/maven-plugin/
        - integration-tests/maven/
        - test-framework/maven/
    - labels: [area/jbang]
      titleBody: "(?i).*jbang.*"
      notify: [quarkusio/devtools, maxandersen]
      directories:
        - "**/*JBang*"
        - "**/*jbang*"
    - labels: [area/codestarts]
      titleBody: "(?i).*codestart.*"
      notify: [quarkusio/devtools, ia3andy]
      directories:
        - independent-projects/tools/codestarts/
        - devtools/platform-descriptor-json/src/main/resources/bundled-codestarts/
        - devtools/platform-descriptor-json/src/main/resources/codestarts/
        - devtools/platform-descriptor-json/src/main/resources/templates/
    - labels: [area/hibernate-reactive, area/persistence]
      titleBody: "(?i).*hibernate.reactive.*"
      notify: [aguibert, gavinking, Sanne]
      directories:
        - extensions/hibernate-reactive
    - labels: [area/hibernate-orm, area/persistence]
      expression: |
              matches(titleBody, "(?i).*hibernate.*")
              && !matches(titleBody, "(?i).*hibernate.validator.*")
              && !matches(titleBody, "(?i).*hibernate.search.*")
      notify: [gsmet, Sanne]
      directories:
        - extensions/hibernate-orm/
        - integration-tests/common-jpa-entities/
        - integration-tests/jpa-derby/
        - integration-tests/jpa-h2/
        - integration-tests/jpa-mariadb/
        - integration-tests/jpa-mssql/
        - integration-tests/jpa-mysql/
        - integration-tests/jpa-postgresql/
        - integration-tests/jpa-without-entity/
        - integration-tests/jpa/
        - integration-tests/infinispan-cache-jpa/
    - labels: [area/hibernate-search]
      titleBody: "(?i).*hibernate.search.*"
      notify: [gsmet, yrodiere]
      directories:
        - extensions/hibernate-search-orm-elasticsearch/
        - integration-tests/hibernate-search-orm-elasticsearch/
        - extensions/elasticsearch-rest-client/
        - extensions/elasticsearch-rest-client-common/
    - labels: [area/elasticsearch]
      titleBody: "(?i).*elasticsearch.*"
      notify: [gsmet, yrodiere, loicmathieu]
      directories:
        - extensions/elasticsearch
        - integration-tests/elasticsearch
    - labels: [area/hibernate-validator]
      titleBody: "(?i).*hibernate.validator.*"
      notify: [gsmet]
      directories:
        - extensions/hibernate-validator/
        - integration-tests/hibernate-validator/
    - labels: [area/jaeger]
      titleBody: "(?i).*jaeger.*"
      notify: [kenfinnigan, pavolloffay]
      directories:
        - extensions/jaeger/
    - labels: [area/kotlin]
      titleBody: "(?i).*kotlin.*"
      notify: [evanchooly]
      directories:
        - extensions/kotlin/
        - integration-tests/kotlin/
    - labels: [area/mongodb]
      titleBody: "(?i).*mongo.*"
      notify: [loicmathieu, evanchooly]
      directories:
        - extensions/mongodb-client/
        - integration-tests/mongodb-client/
        - integration-tests/mongodb-panache/
        - extensions/panache/mongodb-panache/
    - labels: [area/openapi, area/smallrye]
      title: "(?i).*openapi.*"
      notify: [EricWittmann, MikeEdgar, phillip-kruger]
      directories:
        - extensions/smallrye-openapi
    - labels: [area/graphql, area/smallrye]
      title: "(?i).*graphql.*"
      notify: [phillip-kruger, jmartisk]
      directories:
        - extensions/smallrye-graphql/
        - extensions/vertx-graphql/
        - integration-tests/vertx-graphql/
    - labels: [area/tracing, area/smallrye]
      titleBody: "(?i).*(trace|tracing|telemetry).*"
      notify: [kenfinnigan, Ladicek]
      directories:
        - extensions/smallrye-opentracing/
    - labels: [area/security, area/smallrye]
      titleBody: "(?i).*jwt.*"
      notify: [sberyozkin]
    - labels: [area/security]
      titleBody: "(?i).*security.*"
      notify: [sberyozkin]
    - labels: [area/metrics, area/smallrye]
      title: "(?i).*metrics.*"
      notify: [jmartisk]
      directories:
        - extensions/smallrye-metrics
    - labels: [area/metrics]
      title: "(?i).*micrometer.*"
      notify: [ebullient]
      directories:
        - extensions/micrometer
    - labels: [area/health, area/smallrye]
      title: "(?i).*health.*"
      notify: [jmartisk, xstefank]
      directories:
        - extensions/smallrye-health/
    - labels: [area/fault-tolerance, area/smallrye]
      title: "(?i).*fault.tolerance.*"
      notify: [Ladicek]
      directories:
        - extensions/smallrye-fault-tolerance/
    - labels: [area/mutiny, area/smallrye]
      title: "(?i).*mutiny.*"
      notify: [cescoffier, jponge]
      directories:
        - extensions/mutiny/
        - extensions/rest-client-mutiny/
        - extensions/resteasy-mutiny-common/
        - extensions/resteasy-mutiny/
    - labels: [area/panache]
      titleBody: "(?i).*panache.*"
      notify: [FroMage, loicmathieu]
      directories:
        - extensions/panache/
        - integration-tests/hibernate-orm-panache/
    - labels: [area/qute]
      titleBody: "(?i).*qute.*"
      notify: [mkouba]
      directories:
        - extensions/qute/
        - extensions/resteasy-qute/
    - labels: [area/reactive-messaging, area/smallrye]
      titleBody: "(?i).*reactive.messaging.*"
      notify: [cescoffier, kenfinnigan, phillip-kruger]
      directories:
        - extensions/smallrye-reactive-messaging
    - labels: [area/rest-client]
      titleBody: "(?i).*rest.client.*"
      notify: [phillip-kruger]
      directories:
        - extensions/rest-client/
    - labels: [area/smallrye]
      title: "(?i).*smallrye.*"
      notify: [kenfinnigan, phillip-kruger, jmartisk, radcortez, Ladicek]
      directories:
        - extensions/smallrye-
    - labels: [area/spring]
      titleBody: "(?i).*spring.*"
      notify: [geoand]
      directories:
        - extensions/spring-
        - integration-tests/spring-
    - labels: [env/windows]
      titleBody: "(?i).*windows.*"
    - labels: [area/kubernetes]
      titleBody: "(?i).*kubernetes.*"
      notify: [geoand]
      directories:
        - extensions/kubernetes/
        - extensions/kubernetes-client/
        - integration-tests/kubernetes/
        - integration-tests/kubernetes-client/
    - labels: [area/kubernetes]
      titleBody: "(?i).*minikube.*"
      notify: [geoand]
    - labels: [area/kubernetes]
      titleBody: "(?i).*openshift.*"
      notify: [geoand]
    - labels: [area/kubernetes]
      titleBody: "(?i).*knative.*"
      notify: [geoand]
    - labels: [area/container-image]
      titleBody: "(?i).*jib.*"
      notify: [geoand]
    - labels: [area/kafka]
      notify: [cescoffier]
      title: "(?i).*kafka.*"
      directories:
        - extensions/kafka-client/
        - integration-tests/kafka/
    - labels: [area/kafka-streams]
      titleBody: "(?i).*k(afka)?(\\s|-)?stream.*"
      notify: [gunnarmorling, rquinio]
      directories:
        - extensions/kafka-streams
        - integration-tests/kafka-streams/
    - labels: [area/infinispan]
      titleBody: "(?i).*infinispan.*"
      notify: [karesti, wburns]
      directories:
        - extensions/infinispan-client/
        - integration-tests/infinispan-cache-jpa/
        - integration-tests/infinispan-client/
    - labels: [area/grpc]
      titleBody: "(?i).*grpc.*"
      notify: [michalszynkiewicz, cescoffier]
      directories:
        - extensions/grpc-common
        - extensions/grpc
    - labels: [area/scheduler]
      titleBody: "(?i).*schedule(r)?.*"
      notify: [mkouba]
      directories:
        - extensions/scheduler/
    - labels: [area/scheduler]
      titleBody: "(?i).*quartz.*"
      notify: [mkouba, machi1990]
      directories:
        - extensions/quartz/
        - integration-tests/quartz/
    - labels: [area/redis]
      titleBody: "(?i).*redis.*"
      notify: [machi1990, gsmet, cescoffier]
      directories:
        - extensions/redis-client/
        - integration-tests/redis-client/
    - labels: [area/arc]
      title: "(?i).*\\b(arc|cdi|injection)\\b.*"
      notify: [mkouba, manovotn]
      directories:
        - extensions/arc/
        - independent-projects/arc/
    - labels: [area/google-cloud-functions]
      titleBody: "(?i).*google.cloud.*"
      notify: [loicmathieu]
      directories:
        - extensions/google-cloud-functions
        - integration-tests/google-cloud-functions
    - labels: [area/mandrel]
      titleBody: "(?i).*mandrel.*"
      notify: [galderz, zakkak]
    - labels: [area/artemis]
      directories:
        - extensions/artemis-core/
        - extensions/artemis-jms/
        - integration-tests/artemis-core/
        - integration-tests/artemis-jms/
    - labels: [area/cache]
      title: "(?i).*cache.*"
      notify: [gwenneg]
      directories:
        - extensions/cache/
        - integration-tests/cache/
    - labels: [area/cli]
      directories:
        - devtools/cli/
    - labels: [area/config]
      directories:
        - extensions/config-yaml/
        - core/deployment/src/main/java/io/quarkus/deployment/configuration/
        - core/runtime/src/main/java/io/quarkus/runtime/configuration/
    - labels: [area/core]
      directories:
        - core/
    - labels: [area/dependencies]
      directories:
        - .github/dependabot.yml
        - bom/
        - build-parent/
    - labels: [area/devtools]
      directories:
        - devtools/
        - independent-projects/bootstrap/
        - independent-projects/tools/
    - labels: [area/documentation]
      directories:
        - docs/
    - labels: [area/infra-automation]
      directories:
        - .github/
    - labels: [area/jaxb]
      titleBody: "(?i).*jaxb.*"
      notify: [gsmet]
      directories:
        - extensions/jaxb/
    - labels: [area/logging]
      directories:
        - extensions/logging-gelf/
        - extensions/logging-json/
        - extensions/logging-sentry/
        - integration-tests/logging-gelf/
        - core/runtime/src/main/java/io/quarkus/runtime/logging/
        - core/deployment/src/main/java/io/quarkus/logging/
    - labels: [area/narayana]
      directories:
        - extensions/narayana-jta/
        - extensions/narayana-stm/
        - integration-tests/narayana-jta/
        - integration-tests/narayana-stm/
    - labels: [area/neo4j]
      titleBody: "(?i).*neo4j.*"
      notify: [michael-simons]
      directories:
        - extensions/neo4j/
        - integration-tests/neo4j/
    - labels: [area/oidc]
      titleBody: "(?i).*oidc.*"
      notify: [sberyozkin, pedroigor]
      directories:
        - extensions/oidc/
        - integration-tests/oidc/
        - integration-tests/oidc-code-flow/
    - labels: [area/platform]
      directories:
        - independent-projects/tools/
    - labels: [area/reactive]
      directories:
        - extensions/reactive-mysql-client/
        - extensions/reactive-pg-client/
        - extensions/reactive-streams-operators/
        - integration-tests/reactive-mysql-client/
        - integration-tests/reactive-pg-client/
    - labels: [area/resteasy]
      directories:
        - extensions/resteasy
        - integration-tests/resteasy-jackson/
        - integration-tests/elytron-resteasy/
        - integration-tests/virtual-http-resteasy/
    - labels: [area/scala]
      directories:
        - extensions/scala/
        - integration-tests/scala/
    - labels: [area/vault]
      titleBody: vault
      notify: [vsevel]
      directories:
        - extensions/vault/
        - integration-tests/vault
    - labels: [area/vertx]
      directories:
        - extensions/vertx
        - integration-tests/vertx
    - labels: [area/tika]
      titleBody: tika
      notify: [sberyozkin]
      directories:
        - extensions/tika/
        - integration-tests/tika/
    - labels: [area/testing]
      directories:
        - test-framework/
    - labels: [area/undertow]
      directories:
        - extensions/undertow/
        - integration-tests/elytron-undertow/
    - labels: [area/undertow-websockets]
      directories:
        - extensions/undertow-websockets/
    - labels: [area/swagger-ui]
      title: "(?i).*swagger.*"
      notify: [phillip-kruger]
      directories:
        - extensions/swagger-ui/
    - labels: [area/security]
      directories:
        - extensions/security/
        - extensions/elytron
        - extensions/vertx-keycloak/
        - integration-tests/elytron
    - labels: [area/flyway]
      title: "(?i).*flyway.*"
      notify: [cristhiank, geoand, gastaldi, gsmet]
      directories:
        - extensions/flyway/
        - integration-tests/flyway/
    - labels: [area/liquibase]
      title: "(?i).*liquibase.*"
      notify: [andrejpetras, geoand, gsmet]
      directories:
        - extensions/liquibase/
        - integration-tests/liquibase/
