name: Security vulnerability
description: "Report a security issue in Quarkus."
labels: kind/bug
body:
- type: markdown
  attributes:
    value: |
      To report a security vulnerability, please send an email to `security at quarkus dot io` with all the details.

      :warning: Do NOT create a public issue on GitHub. See our [security policy](https://github.com/quarkusio/quarkus/security/policy) for more details.
