name: Quarkus CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  attach-pr-id:
    name: Attach pull request number
    if: github.event_name == 'pull_request'
    steps:
      - name: Create file
        shell: bash
        run: echo $GITHUB_EVENT_NUMBER > pull_request_number
      - name: Upload pull request number
        uses: actions/upload-artifact@v2
        with:
          name: pull_request_number
          path: pull_request_number
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 16 ]
      fail-fast: false
    name: Build Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B clean install --fail-at-end
#      - name: Get temp directory
#        id: get-temp-directory
#        run: |
#          echo "::set-output name=name::$(mktemp -d --suffix '-surefire-reports')"
#      - name: Prepare failure archive (if maven failed)
#        if: failure()
#        shell: bash
#        run: |
#          reportsdir=${{ steps.get-temp-directory.outputs.name }}/surefire-reports
#          mkdir ${reportsdir}
#          find . -name 'TEST-*.xml' -exec cp --parents {} ${reportsdir} \;
      - name: Upload failure Archive (if maven failed)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-jvm-${{matrix.java}}
          path: "**/target/surefire-reports/TEST-*.xml"
#          path: ${{ steps.get-temp-directory.outputs.name }}/surefire-reports
