name: Groovy

on:
  pull_request:
  issues:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  env:
    PULL_REQUEST_NUMBER_ENV_GLOBAL: totoz
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: JVM Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Groovy
        run: |
          curl -s "https://get.sdkman.io" | bash
          sdk install groovy
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          groovy .github/test.groovy
        shell: bash
        env:
          PULL_REQUEST_NUMBER_ENV_LOCAL: totoz
