name: Long CI

on:
  push:
    branches: "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }} && ref = ${{ github.event.ref }} && pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Simulate long build
        shell: bash
        run: |
          sleep 60
