name: Long CI

on:
  push:
    branches: "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Simulate long build
        shell: bash
        run: |
          sleep 60
